### ISSUE TITLE
License in package.xml

### ISSUE THREAD

**Issue by shr-project** [ros2-gbp/navigation2-release#1]
Currently
https://github.com/SteveMacenski/navigation2-release/blob/release/dashing/nav2_amcl/package.xml#L21
says only LGPL, while:
https://github.com/SteveMacenski/navigation2-release/blob/release/dashing/nav2_amcl/src/main.cpp#L3
https://github.com/SteveMacenski/navigation2-release/blob/release/dashing/nav2_amcl/test/unit/test_localization_amcl.cpp#L3
says Apache-2
https://github.com/SteveMacenski/navigation2-release/blob/release/dashing/nav2_amcl/src/amcl_node.cpp#L5
https://github.com/SteveMacenski/navigation2-release/blob/release/dashing/nav2_amcl/include/nav2_amcl/amcl_node.hpp#L5
says LGPL-2.1+

superflore maps this to LGPL-2 in:
https://github.com/ros-infrastructure/superflore/blob/master/superflore/utils.py#L179
and LGPL-2 isn't valid SPDX Identifier in:
https://spdx.org/licenses/
so it would be better to declare the license correctly at the source - in package.xml.

**Comment by SteveMacenski** [comment]
Hi,
This is just the release repo, it would be easier to post this ticket in the main ros-planning/navigation2 repo. 

Keep in mind this is an open source project with many cooks in the kitchen. Some people’s additions will be potentially under different licenses than the original.

**Comment by SteveMacenski** [comment]
This has been resolved.
