### ISSUE TITLE
fix for demos for ubuntu 22 with humble

### ISSUE THREAD

**Issue by altineller** [ros2-gbp/navigation2-release#2]
Running 'ros2 launch nav2_simple_commander nav_to_pose_example_launch.py' causes gazebo to black out for a long time, and when gazebo becomes available the robot is missing, but functioning, which means only the dae files for visuals are not loaded correctly.

I have changed the following lines from turtlebot3_waffle to:

              <uri>model://turtlebot3_common/meshes/waffle_base.dae</uri>
              <uri>model://turtlebot3_common/meshes/lds.dae</uri>
              <uri>model://turtlebot3_common/meshes/tire.dae</uri>
              <uri>model://turtlebot3_common/meshes/tire.dae</uri>

and now all the demos are working, with turtlebot showing in simulation.

I have peeked over to turtlebot3_waffle/meshes/.. and found out there are no mesh files, but the dae files are contained in the turtlebot3_common/meshes directory.

Best Regards,
Can

**Comment by SteveMacenski** [comment]
I'm not sure I see what we can do about that w.r.t. Nav2. Are these modifications to Nav2's URDFs or to Turtlebot 3 package's? If TB3, you need to file with them. If Nav2, if you point me to where the changes are necessary, I'm happy to resolve the issue

**Comment by altineller** [comment]
just modification to 1 file, warehouse.world, located at /opt/ros/humble/share/nav2_simple_commander/warehouse.world

it is not a tb3 issue, tb3 changed their layout of where they store the dae files, and the world file did not.

Best Regards,
Can

**Comment by SteveMacenski** [comment]
Got it- I can do something about that. Thanks for the info.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/3495
